### PR TITLE
replace filesystems storage paths when app is built.

### PR DESCRIPTION
**Pull request by digitalkreativ**
https://github.com/laravel-zero/laravel-zero/issues/177

Provides a BuiltServiceProvider that will replace filesystems app storage paths with current working directory when the  app is built ( phar file, production is true)

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks @digitalkreativ for this PR. And sorry for the late response.

Can you add some tests on this PR?

**Comment by digitalkreativ** [comment]
No problem on the late response. Life gets busy sometimes.

I'll try to get it on the latest laravel zero version and add tests later this week. Might even revisit the code and see if there are improvements that can be made.

Do the tests actually need to built a phar or is it ok to check for production like the code does at the moment?

**Comment by nunomaduro** [comment]
Thanks! Please target the `develop` branch.

The tests don't need to the build the phar. If is not asking for too much, try to isolate the code responsable to check if you are in `phar` mode, and mock it in your test.

**Comment by nunomaduro** [comment]
@digitalkreativ Sorry for this, didn't had time yet to check this. Let's keep it open.

**Comment by digitalkreativ** [comment]
@nunomaduro so sorry I just have not found the time yet to update this. 
When I do I'll close this pull request and open a new one for the develop branch.

**Comment by nunomaduro** [comment]
No need to say sorry, we are doing open source for fun.

**Comment by nunomaduro** [comment]
Closing this for now, don't hesitate to update the pull request if you find time for this.

**Pull request closed without merging**
