### PR TITLE
[5.7] Adding component to register Laravel Events commands

### PR DESCRIPTION
**Pull request by orediggerco**
Ok, here we go for round 2! Adding Illuminate\Foundation made a huge difference in implementing this one. And it should make additional components a breeze too.

Let me know what you think!

### CODE REVIEW

**Comment by orediggerco** [comment]
These tests all worked for me locally, but I'll look into why they are failing when run by CI.

**Comment by nunomaduro** [comment]
Thanks @orediggerco for your contribution! I am currently in holidays! I will take a look as soon as possible! Thanks again! 👍

**Comment by nunomaduro** [comment]
@orediggerco Did you manage to make it work without the `illuminate/broadcasting` dependency?

**Comment by orediggerco** [comment]
Hi there, sorry for the delay!

Yes, that package shouldn't be needed. The only illuminate packages I see in a composer show are:
```
illuminate/cache                      v5.6.11 The Illuminate Cache package.
illuminate/config                     v5.6.11 The Illuminate Config package.
illuminate/console                    v5.6.11 The Illuminate Console package.
illuminate/container                  v5.6.11 The Illuminate Container package.
illuminate/contracts                  v5.6.11 The Illuminate Contracts package.
illuminate/database                   v5.6.11 The Illuminate Database package.
illuminate/events                     v5.6.11 The Illuminate Events package.
illuminate/filesystem                 v5.6.11 The Illuminate Filesystem package.
illuminate/log                        v5.6.11 The Illuminate Log package.
illuminate/support                    v5.6.11 The Illuminate Support package.
```

**Comment by nunomaduro** [comment]
@orediggerco Ok! I will probably merge into 5.7. Like that I can present this as Laravel Zero 5.7 feature.

**Comment by orediggerco** [comment]
Sounds great! Let me know if you need anything from me on this in the meantime.

**Comment by nunomaduro** [comment]
I am sorry @orediggerco. No plans ATM for merging this. 🙁

**Pull request closed without merging**
