### PR TITLE
feat: add support for PHP 8.1

### PR DESCRIPTION
**Pull request by owenvoke**
This is a PR where I'll just add any work on adding PHP 8.1 support to Laravel Zero. 👍🏻

Waiting on PHP 8.1 support for [Box](https://github.com/box-project/box), ~~weirdly on my local macOS setup, I get a bunch of errors for Pest however CI is showing green...~~

### CODE REVIEW

**Comment by nunomaduro** [comment]
@owenvoke You need to bump the framework dependency to the latest.

**Comment by nunomaduro** [comment]
Yes you need. But the issue here is that you need to bump this list the their latest versions: https://github.com/laravel-zero/framework/blob/master/composer.json#L17.

**Comment by owenvoke** [comment]
Looks like there are things that we don't currently require directly, but are required by Illuminate components we use, that don't resolve to the required versions. Should these be added as dependencies to LZ, or be updated in Laravel?

For example, `illuminate/collections`, which is required at `^8.0` by pretty much all the Illuminate packages we use. However,  we don't require it in LZ, so it installs the lowest version possible (8.12.0).

---

On another note, I'm surprised that Laravel don't test against lowest versions for PHP 8.1 yet.

**Comment by nunomaduro** [comment]
We should add ` illuminate/collections` to our composer json.

**Comment by owenvoke** [comment]
Ok, I'll do that 👍🏻

**Comment by owenvoke** [comment]
I think this is ok to be merged, the update to Box for supporting PHP 8.1 will need to be done separately.

**Pull request merged**
