### PR TITLE
Fix support for Linux OS

### PR DESCRIPTION
**Pull request by def-studio**
It seems that the git.version closure fails if launched from a Linux shell and the computed result is _unreleased_

image

that's because the `$(git rev-list --tags --max-count=1)` command returns a newline character at the end of the string

i've tested it by writing a custom command with this:
```
$process = tap(new Process(['git', 'rev-list', '--tags', '--max-count=1'], app()->basePath()))->run();
dd($process->getOutput());
```
and will output this:

image

and this breaks the command `git describe --tags $(git rev-list --tags --max-count=1)` if executed through `Process->run()`

so I've changed the Windows fix in order to execute its code even in a linux environment:
```
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'  || strtoupper(PHP_OS) === 'LINUX')
```

this way the git.version is detected without any problem even in a Linux system:

image

**Additional Note**: what's the point of executing `git describe --tags $(git rev-list --tags --max-count=1)`  instead of two distinct steps? wouldn't result a cleaner code if we always make two separate calls to `Process->run()` and trimming the results instead of adding a check for OS name?

### CODE REVIEW

**Comment by def-studio** [comment]
@owenvoke any news?

**Comment by owenvoke** [comment]
Apologies, I haven't had time to boot up my Linux machine. This looks fine though. 👍🏻

I agree that it would probably be easier to always make 2 calls, but I think it may originally have been done so that it doesn't need to create 2 shells which is slower? 🤔 It looks like this is the case on MacOS as well, so it may have been a change to Git to add a trailing newline. I'd be pretty happy to just remove the `if` statement and always run both if that's easier? 🤷🏻

I think we might be able to use `--abbrev=0` in the `git describe` which would allow it to be one shell call afaik. 🤔

```php
final class GitVersionServiceProvider extends ServiceProvider
{
    /** {@inheritdoc} */
    public function register(): void
    {
        $this->app->bind(
            'git.version',
            function (Application $app) {
                $task = ['git', 'describe', '--tags', '--abbrev=0'];

                $process = tap(new Process($task, $app->basePath()))->run();

                return trim($process->getOutput()) ?: 'unreleased';
            }
        );
    }
}
```

**Comment by def-studio** [comment]
thanks for your reply and sorry for my bump :)

+1 for your `--abbrev=` solution

I have updated the PR with your code and seems to work fine for me

**Comment by owenvoke** [comment]
That's great. 👍🏻 I'll just test it on Windows, and then this should be good to go. 🎉

**Review by owenvoke — APPROVED** [review]

**Pull request merged**
