### PR TITLE
fix: add support for Box compilation on PHP 8.1

### PR DESCRIPTION
**Pull request by owenvoke**
This needs further testing, but should add support for compilation on PHP 8.1 to Laravel Zero 8 applications, while continuing to support PHP 7.3 to 8.0 👍🏻

### CODE REVIEW

**Comment by defunctl** [comment]
I was unable to test PHP 7.3 for this as I no longer have it installed, but I successfully built and used the phar with:

1. PHP 7.4.27
2. PHP 8.0.13
3. PHP 8.1.2

PHP `error_reporting = E_ALL` and no notices, errors, or warnings.

**Comment by defunctl** [comment]
Also verified the phar itself does not have the framework/bin folder:

image

**Comment by owenvoke** [comment]
Thank you for that @defunctl, I'll get this tested on PHP 7.3 today, and then merge and release a new 8.x. 👍🏻

**Comment by defunctl** [comment]
@owenvoke successfully built my CLI tool into a phar in a  `PHP 7.3.31` docker container. 

Works fine running under 7.3 and the typical warnings if using the packaged phar under PHP 8.1:

```
PHP Deprecated:  Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///...
```

What's more interesting is that the phar built using PHP 8.1 works perfectly fine on 7.3, which is great.

**Pull request merged**
