### PR TITLE
Removing the TestCommand when compiling.

### PR DESCRIPTION
**Pull request by wotta**
This pr closes https://github.com/laravel-zero/laravel-zero/issues/277
Updated LoadConfigurationsTest.php; 
Added a test to make sure the `make:test` command is removed.

### CODE REVIEW

**Comment by wotta** [comment]
@owenvoke I just commited your suggested changes but I am getting a few errors now.

> Class NunoMaduro\Collision\Adapters\Laravel\Commands\TestCommand not found.

I have also merged the 7.* branch in my and composer test command does also fail at this moment.

**Comment by owenvoke** [comment]
I think that the test is failing because when it is run, the environment is in development mode. I'm not sure the best way to cope with this. 🤔

It also looks like the test command doesn't actually get removed in production, due to the reflection code only being passed the `$toRemoveCommands` variable. This should be fixable by using the following instead:
```diff
- $commands = $commands->diff(array_merge($toRemoveCommands, $toRemoveLaravelCommands ?? []));
+ $toRemoveCommands = array_merge($toRemoveCommands, $toRemoveLaravelCommands ?? []);
+ $commands = $commands->diff($toRemoveCommands);
```

**Comment by wotta** [comment]
@owenvoke I would like to things one step at the time and do the refactor at a later moment if you don't mind. Would like to get familiar with the core code so I understand how it is running 🙂 

At this moment I am trying to switch the environment. Since the main configuration is made for the "development" environment.

**Comment by owenvoke** [comment]
The refactor can be done at another time, I was just making a note of it. :+1:

I've had some issues while changing the env in tests too.

**Comment by wotta** [comment]
Yeah I got stuck after researching a bit. Basically what I have tried is changing the env on runtime using the `ConfigRepository`, using the `config()` helper and trying reinitiate the `app` with the changed values.

This hasn't worked unfortunately so I am waiting for @nunomaduro to answer your ping 🙂

**Comment by danielsuguimoto** [comment]
How about using `putenv`?
https://www.php.net/manual/pt_BR/function.putenv.php

**Comment by wotta** [comment]
I tried but it seems like the "test application" is created with the files in the application folder.
One thing I could try is to create an extra configuration file that will overwrite the normal one and call the `refreshApplication` method.

This should hopefully create the application with the new environment value which allows me to run the test and see it pass.

I will try to do this in the afternoon.

**Comment by danielsuguimoto** [comment]
I'm not sure if it is possible, but you could also try to mock the environment, instead of using the 'real' one

**Comment by wotta** [comment]
Hmm I will try this when I'm home.

**Comment by wotta** [comment]
@owenvoke, @nunomaduro I got the test working. Is this enough to move forward?

**Comment by owenvoke** [comment]
Great! I'll have a look into this shortly.

**Comment by owenvoke** [comment]
@wotta, is it ok to make this "Ready for review"?

----

Also, seems to be working great in an app!

Screenshot from 2020-03-12 23-05-23

**Comment by wotta** [comment]
Awesome! It can be set to ready for review.

**Comment by peterjaap** [comment]
Great job everybody

**Comment by wotta** [comment]
@peterjaap thanks for thinking along!

**Pull request merged**
