### PR TITLE
feat: add Redis component

### PR DESCRIPTION
**Pull request by owenvoke**
Closes https://github.com/laravel-zero/website/pull/39

### CODE REVIEW

**Comment by nunomaduro** [comment]
@owenvoke Would this feature would be useful for people? Can you give me a snippet example?

**Comment by owenvoke** [comment]
I probably wouldn't use it, but back on https://github.com/laravel-zero/website/pull/39 you mentioned it would be nice as a component.

**Comment by nunomaduro** [comment]
My question is more like: After people install the component. What code can they use to use redis?

**Comment by owenvoke** [comment]
Ohhh. Whoops. I guess they can use it with the `queue` or `database` components. For example you could make a CLI tool for viewing or managing Redis tasks.
https://laravel.com/docs/8.x/redis

Or you could use the facade with `Redis::get()` or `Redis::set()` for storing any data.

**Review by nunomaduro — APPROVED** [review]
Makes sense. So let's make sure you put those on docs. Looks good to merge.

**Comment by owenvoke** [comment]
I'll write the docs for this later and then merge. 👍🏻 Thanks Nuno.

**Pull request merged**
