### PR TITLE
Fixing build command cancellation

### PR DESCRIPTION
**Pull request by danielsuguimoto**
Ensure clear is called after CTRL+C signal

### CODE REVIEW

**Comment by pxgamer** [comment]
Hi @danielsuguimoto, thanks for the PR!

I'll be able to take a look at this later today. 👌

**Comment by theofidry** [comment]
Note that `pcntl` is not necessarily installed neither does it work well on Windows IIRC

**Comment by pxgamer** [comment]
Thanks @theofidry for flagging that up. That might be an issue as it looks like at some point we'd like to support Windows builds. Although, currently builds aren't working on Windows anyway (as per #348).

I assume it's not possible for this to be implemented with something like a `__destruct()` method? 🤔

If this were to be merged, I also think `ext-pcntl` should be added to the Composer requirements.

**Comment by danielsuguimoto** [comment]
Should we wait for php 7.4 official release before thinking about windows support?

https://github.com/php/php-src/blob/PHP-7.4/UPGRADING#L681

**Comment by pxgamer** [comment]
Sorry for the delayed reply, I haven't yet been able to test this as I've been away. From that UPGRADING doc, I'm not sure this will resolve the incompatibility of PCNTL with Windows. However, the `sapi_windows_set_ctrl_handler()` function does sound quite useful, although this would mean that Laravel Zero requires PHP 7.4 I guess? 🤔

I do think it's probably worth waiting though as it's out next month!

---

Back to this PR though, as mentioned in my previous comment, I think that `ext-pcntl` would need to be added to the Composer requirements (not really a huge fan of requiring more extensions personally). Or, maybe add an `if` statement around this to check if the extension is loaded? 🤔

I'm not really sure about this as I haven't used PCNTL much. But I will test later today if I get the time. 👍

**Comment by danielsuguimoto** [comment]
@pxgamer no worries, no rush. I don't like adding more extensions either and adding an `if` statement sounds a good plan. It's your call...

**Comment by dbpolito** [comment]
Laravel itself uses it on the Queue component and here is how they handle it:

https://github.com/laravel/framework/blob/master/src/Illuminate/Queue/Worker.php#L560
https://github.com/laravel/framework/blob/master/composer.json#L119

So adding an if checking if the extension is loaded and adding as a suggestion to `composer.json` should do the trick :+1: 

I remember Dusk having this very same problem, as they change `.env` at runtime,  doing this very same approach there would be a very good contribution there too. ❤️

**Comment by pxgamer** [comment]
I think that sounds good @dbpolito 👌

Would you like to add this @danielsuguimoto, and then I think it should be fine to merge!

**Comment by danielsuguimoto** [comment]
Thanks for the great tips @dbpolito 

@pxgamer Yep, it looks like we have a plan now! I'm adding this soon!

**Comment by danielsuguimoto** [comment]
@pxgamer about the suggestion message, do you have something in mind? Sorry, English isn't my native language...

**Comment by pxgamer** [comment]
Sorry again for the delay, I seem to have missed the notification.

I have no idea how this should be worded. It's a bit of a weird thing. Maybe something like:
> Required to ensure that data is cleared when cancelling the build process.

**Pull request merged**
