### PR TITLE
Update workflow to also test on PHP 8

### PR DESCRIPTION
**Pull request by abenettt**
With the upcoming release of `PHP 8` it might be prudent to also test against it as to catch errors early.
Failing tests on `PHP 8` do not cause the workflow to fail as it is not yet released but it gives an indication on what still needs to be done to reach compatibility.

### CODE REVIEW

**Comment by owenvoke** [comment]
I think this is worth adding to Laravel Zero 8 (the `develop` branch) instead of LZ7. 🤔

**Comment by abenettt** [comment]
Ah yeah, I can update the target branch.
If we just add `'8.0'` to the matrix the whole workflow will fail if the tests on `'8.0'` fail and we might not want this. We want to see them failing but not impacting the rest of the workflow. As `PHP 8` is still a few months from being released I think this is ok. Of course when `PHP 8` is released in November we can just update the workflow again to treat `'8.0'` just like any other `PHP` version but until then I think we should keep it like that.

**Comment by owenvoke** [comment]
Cheers! Lets see how that runs. 🥳

**Review by owenvoke — APPROVED** [review]
LGTM! Thanks @abenettt. 🥳

**Comment by owenvoke** [comment]
Uh... what 🤔 Merging this actually applied [your squash commit](https://github.com/laravel-zero/framework/commit/9d1f8e63430c68f47d3a47ec1f25c96cf319add6) and removed a load of the history from the [`develop` branch](https://github.com/laravel-zero/framework/commits/develop).

**Pull request merged**
