### PR TITLE
Use proper check to see if TTY is supported

### PR DESCRIPTION
**Pull request by paneidos**
The old check failed in CI environments, making automatic builds impossible.

Not sure about a test for this, the existing build test mocks the composer part.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@paneidos That method exists only in `symfony/process` 4.1. The component `illuminate/console` requires the "symfony/console", and "symfony/console" only requires `symfony/process` - "~3.4|~4.0". 

For this reason: Unfortunately that may be a breaking change. Shouldn't we consider merge this only in `develop` branch? Only for Laravel Zero 5.7?

**Comment by paneidos** [comment]
Hadn't considered the fact that older versions of `symfony/process` don't have the method. I'll go check if  adding an `is_writable()` check to 5.6 will make it work in our CI environment.

**Comment by paneidos** [comment]
Check with `is_writable` didn't work. The only way to make it work is to either copy the logic from `symfony/process` or ignore errors at this point. Ignoring any errors seems fine at this point and makes sure the code keeps working if `symfony/process` uses a different implementation in the future.

**Comment by nunomaduro** [comment]
Thanks.

**Pull request merged**
