### PR TITLE
Add logo component

### PR DESCRIPTION
**Pull request by victorlap**
As per laravel-zero/laravel-zero#163 

I am not too sure about the naming, and the testing of the component does not work atm. I couldn't get the different application instances to work properly. However, the component works, even if the test does not confirm that.

Screenshot

Edit: I changed the test such that it passes.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@victorlap Are you up to add some docs about this? [https://github.com/laravel-zero/website](https://github.com/laravel-zero/website) 👍

**Comment by victorlap** [comment]
Off course! Will look at it later this week.

**Comment by nunomaduro** [comment]
@victorlap Do you have twitter handler?

**Comment by victorlap** [comment]
My twitter handle is @iamvictorlap

**Pull request merged**
